name: Node.js CI

on:
  push:
    branches:
      - testing
      - master
      - develop
  pull_request:
    branches:
      - testing
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - run: grep resolved package-lock.json | grep -vq akamai || echo "package-lock.json contains invalid entries" && exit 1
      shell: bash --noprofile --norc {0}
      name: Validate package-lock.json file

    - uses: actions/setup-node@v1
      name: Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present

    - run: touch /tmp/test-edgerc
    - run: ./akamai-sandbox --edgerc /tmp/test-edgerc help
      name: Run sandbox command
      env:
        AKAMAI_CLI_CACHE_PATH: /tmp
